### ISSUE TITLE
Extensions Not Working in Latest ChatGPT Release (2024/09/16)

### ISSUE THREAD

**Issue by eightsuzuki** [yuta-nishi/block-enter#126] opened 2024-09-16 04:55 UTC
### Overview:
After updating to the latest version of ChatGPT released on September 16, 2024, extensions are not functioning as expected. Specifically, the extensions are not recognized or fail to execute even when enabled.

### Environment:
- **ChatGPT Version**: 2024/09/16 latest version
- **Operating System**: MacOS
- **Browser**: Chrome

**Comment by yuta-nishi** [comment] 2024-09-21 09:30
Thanks for the bug report!
It was caused by a change in the implementation of the ChatGPT page.

The corresponding implementation has been merged into main!

**Closed by yuta-nishi** 2024-09-21 09:30 UTC
